version: '3'
services:
  backend:
    container_name: trybe_hotel_backend
    build: ./src/TrybeHotel
    ports:
      - "5001:80"
    working_dir: /app-backend
    volumes:
      - ./src/TrybeHotel:/app-backend
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: trybe_hotel_db_fase_d
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TrybeHotel12!
      - MSSQL_PID=Developer